#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC36CDCB4DF00C68C (infra-root@openstack.org)
#
Name     : horizon
Version  : 13.0.1
Release  : 63
URL      : http://tarballs.openstack.org/horizon/horizon-13.0.1.tar.gz
Source0  : http://tarballs.openstack.org/horizon/horizon-13.0.1.tar.gz
Source1  : horizon.tmpfiles
Source2  : http://tarballs.openstack.org/horizon/horizon-13.0.1.tar.gz.asc
Summary  : OpenStack Dashboard
Group    : Development/Tools
License  : Apache-2.0
Requires: horizon-config = %{version}-%{release}
Requires: horizon-license = %{version}-%{release}
Requires: horizon-python = %{version}-%{release}
Requires: horizon-python3 = %{version}-%{release}
Requires: Babel
Requires: Django
Requires: Pint
Requires: PyYAML
Requires: XStatic
Requires: XStatic-Angular
Requires: XStatic-Angular-Bootstrap
Requires: XStatic-Angular-FileUpload
Requires: XStatic-Angular-Gettext
Requires: XStatic-Angular-Schema-Form
Requires: XStatic-Angular-lrdragndrop
Requires: XStatic-Bootstrap-Datepicker
Requires: XStatic-Bootstrap-SCSS
Requires: XStatic-D3
Requires: XStatic-Font-Awesome
Requires: XStatic-Hogan
Requires: XStatic-JQuery-Migrate
Requires: XStatic-JQuery.TableSorter
Requires: XStatic-JQuery.quicksearch
Requires: XStatic-JSEncrypt
Requires: XStatic-Jasmine
Requires: XStatic-Rickshaw
Requires: XStatic-Spin
Requires: XStatic-bootswatch
Requires: XStatic-jQuery
Requires: XStatic-jquery-ui
Requires: XStatic-mdi
Requires: XStatic-objectpath
Requires: XStatic-roboto-fontface
Requires: XStatic-smart-table
Requires: XStatic-term.js
Requires: XStatic-tv4
Requires: django-babel
Requires: django-pyscss
Requires: django_compressor
Requires: futurist
Requires: iso8601
Requires: keystoneauth1
Requires: netaddr
Requires: oslo.concurrency
Requires: oslo.config
Requires: oslo.i18n
Requires: oslo.policy
Requires: oslo.serialization
Requires: oslo.utils
Requires: osprofiler
Requires: pbr
Requires: pyScss
Requires: pymongo
Requires: python-cinderclient
Requires: python-glanceclient
Requires: python-keystoneclient
Requires: python-neutronclient
Requires: python-novaclient
Requires: python-swiftclient
Requires: pytz
Requires: semantic_version
Requires: six
BuildRequires : Babel
BuildRequires : Django
BuildRequires : Pint
BuildRequires : PyYAML
BuildRequires : XStatic
BuildRequires : XStatic-Angular
BuildRequires : XStatic-Angular-Bootstrap
BuildRequires : XStatic-Angular-FileUpload
BuildRequires : XStatic-Angular-Gettext
BuildRequires : XStatic-Angular-Schema-Form
BuildRequires : XStatic-Angular-lrdragndrop
BuildRequires : XStatic-Bootstrap-Datepicker
BuildRequires : XStatic-Bootstrap-SCSS
BuildRequires : XStatic-D3
BuildRequires : XStatic-Font-Awesome
BuildRequires : XStatic-Hogan
BuildRequires : XStatic-JQuery-Migrate
BuildRequires : XStatic-JQuery.TableSorter
BuildRequires : XStatic-JQuery.quicksearch
BuildRequires : XStatic-JSEncrypt
BuildRequires : XStatic-Jasmine
BuildRequires : XStatic-Magic-Search
BuildRequires : XStatic-Rickshaw
BuildRequires : XStatic-Spin
BuildRequires : XStatic-bootswatch
BuildRequires : XStatic-jQuery
BuildRequires : XStatic-jquery-ui
BuildRequires : XStatic-mdi
BuildRequires : XStatic-objectpath
BuildRequires : XStatic-roboto-fontface
BuildRequires : XStatic-smart-table
BuildRequires : XStatic-term.js
BuildRequires : XStatic-tv4
BuildRequires : buildreq-distutils3
BuildRequires : django-appconf
BuildRequires : django-babel
BuildRequires : django-nose
BuildRequires : django-pyscss
BuildRequires : django_compressor
BuildRequires : eventlet
BuildRequires : futurist
BuildRequires : httplib2
BuildRequires : iso8601
BuildRequires : keystoneauth1
BuildRequires : kombu
BuildRequires : netaddr
BuildRequires : nose
BuildRequires : oslo.concurrency
BuildRequires : oslo.config
BuildRequires : oslo.i18n
BuildRequires : oslo.policy
BuildRequires : oslo.serialization
BuildRequires : oslo.utils
BuildRequires : osprofiler
BuildRequires : pathlib
BuildRequires : pbr
BuildRequires : prettytable
BuildRequires : pyScss
BuildRequires : pymongo
BuildRequires : python-ceilometerclient
BuildRequires : python-cinderclient
BuildRequires : python-glanceclient
BuildRequires : python-heatclient
BuildRequires : python-keystoneclient
BuildRequires : python-neutronclient
BuildRequires : python-novaclient
BuildRequires : python-saharaclient
BuildRequires : python-swiftclient
BuildRequires : python-troveclient
BuildRequires : pytz
BuildRequires : rjsmin
BuildRequires : six
BuildRequires : stevedore
Patch1: 0001-enable-dashboard-in-apache.patch
Patch2: 0002-nginx-uwsgi.patch
Patch3: 0001-stateless.patch
Patch4: nodeps.patch

%description
=============================
Horizon (OpenStack Dashboard)
=============================

Horizon is a Django-based project aimed at providing a complete OpenStack
Dashboard along with an extensible framework for building new dashboards
from reusable components. The ``openstack_dashboard`` module is a reference
implementation of a Django site that uses the ``horizon`` app to provide
web-based interactions with the various OpenStack projects.

* Release management: https://launchpad.net/horizon
* Blueprints and feature specifications: https://blueprints.launchpad.net/horizon
* Issue tracking: https://bugs.launchpad.net/horizon

.. image:: https://governance.openstack.org/tc/badges/horizon.svg
    :target: https://governance.openstack.org/tc/reference/tags/index.html

Using Horizon
=============

See ``doc/source/install/index.rst`` about how to install Horizon
in your OpenStack setup. It describes the example steps and
has pointers for more detailed settings and configurations.

It is also available at
`Installation Guide <https://docs.openstack.org/horizon/latest/install/index.html>`_.

Getting Started for Developers
==============================

``doc/source/quickstart.rst`` or
`Quickstart Guide <https://docs.openstack.org/horizon/latest/contributor/quickstart.html>`_
describes how to setup Horizon development environment and start development.

Building Contributor Documentation
==================================

This documentation is written by contributors, for contributors.

The source is maintained in the ``doc/source`` directory using
`reStructuredText`_ and built by `Sphinx`_

.. _reStructuredText: http://docutils.sourceforge.net/rst.html
.. _Sphinx: http://sphinx-doc.org/

To build the docs, use::

  $ tox -e docs

Results are in the ``doc/build/html`` directory

%package config
Summary: config components for the horizon package.
Group: Default

%description config
config components for the horizon package.


%package license
Summary: license components for the horizon package.
Group: Default

%description license
license components for the horizon package.


%package python
Summary: python components for the horizon package.
Group: Default
Requires: horizon-python3 = %{version}-%{release}

%description python
python components for the horizon package.


%package python3
Summary: python3 components for the horizon package.
Group: Default
Requires: python3-core
Provides: pypi(horizon)

%description python3
python3 components for the horizon package.


%prep
%setup -q -n horizon-13.0.1
cd %{_builddir}/horizon-13.0.1
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582935451
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fcf-protection=full -fno-lto -fstack-protector-strong "
export FCFLAGS="$CFLAGS -fcf-protection=full -fno-lto -fstack-protector-strong "
export FFLAGS="$CFLAGS -fcf-protection=full -fno-lto -fstack-protector-strong "
export CXXFLAGS="$CXXFLAGS -fcf-protection=full -fno-lto -fstack-protector-strong "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
/bin/bash run_tests.sh -N --no-pep8 || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/horizon
cp %{_builddir}/horizon-13.0.1/LICENSE %{buildroot}/usr/share/package-licenses/horizon/294b43b2cec9919063be1a3b49e8722648424779
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/tmpfiles.d/horizon.conf
## install_append content

## install_append end

%files
%defattr(-,root,root,-)

%files config
%defattr(-,root,root,-)
/usr/lib/tmpfiles.d/horizon.conf

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/horizon/294b43b2cec9919063be1a3b49e8722648424779

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
