#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC36CDCB4DF00C68C (infra-root@openstack.org)
#
Name     : horizon
Version  : 13.0.1
Release  : 50
URL      : http://tarballs.openstack.org/horizon/horizon-13.0.1.tar.gz
Source0  : http://tarballs.openstack.org/horizon/horizon-13.0.1.tar.gz
Source1  : horizon.tmpfiles
Source99 : http://tarballs.openstack.org/horizon/horizon-13.0.1.tar.gz.asc
Summary  : OpenStack Dashboard
Group    : Development/Tools
License  : Apache-2.0
Requires: horizon-python3
Requires: horizon-config
Requires: horizon-license
Requires: horizon-python
Requires: Babel
Requires: Django
Requires: Pint
Requires: PyYAML
Requires: XStatic
Requires: XStatic-Angular
Requires: XStatic-Angular-Bootstrap
Requires: XStatic-Angular-Gettext
Requires: XStatic-Angular-lrdragndrop
Requires: XStatic-Bootstrap-Datepicker
Requires: XStatic-Bootstrap-SCSS
Requires: XStatic-D3
Requires: XStatic-Font-Awesome
Requires: XStatic-Hogan
Requires: XStatic-JQuery-Migrate
Requires: XStatic-JQuery.TableSorter
Requires: XStatic-JQuery.quicksearch
Requires: XStatic-JSEncrypt
Requires: XStatic-Jasmine
Requires: XStatic-Rickshaw
Requires: XStatic-Spin
Requires: XStatic-bootswatch
Requires: XStatic-jQuery
Requires: XStatic-jquery-ui
Requires: XStatic-mdi
Requires: XStatic-roboto-fontface
Requires: XStatic-smart-table
Requires: XStatic-term.js
Requires: django-babel
Requires: django-pyscss
Requires: futurist
Requires: iso8601
Requires: keystoneauth1
Requires: netaddr
Requires: oslo.concurrency
Requires: oslo.config
Requires: oslo.i18n
Requires: oslo.policy
Requires: oslo.serialization
Requires: oslo.utils
Requires: osprofiler
Requires: pbr
Requires: pyScss
Requires: pymongo
Requires: python-cinderclient
Requires: python-glanceclient
Requires: python-keystoneclient
Requires: python-neutronclient
Requires: python-novaclient
Requires: python-swiftclient
Requires: pytz
Requires: semantic_version
Requires: six
BuildRequires : Babel
BuildRequires : Django
BuildRequires : Pint
BuildRequires : PyYAML
BuildRequires : XStatic
BuildRequires : XStatic-Angular
BuildRequires : XStatic-Angular-Bootstrap
BuildRequires : XStatic-Angular-Gettext
BuildRequires : XStatic-Angular-lrdragndrop
BuildRequires : XStatic-Bootstrap-Datepicker
BuildRequires : XStatic-Bootstrap-SCSS
BuildRequires : XStatic-D3
BuildRequires : XStatic-Font-Awesome
BuildRequires : XStatic-Hogan
BuildRequires : XStatic-JQuery-Migrate
BuildRequires : XStatic-JQuery.TableSorter
BuildRequires : XStatic-JQuery.quicksearch
BuildRequires : XStatic-JSEncrypt
BuildRequires : XStatic-Jasmine
BuildRequires : XStatic-Magic-Search
BuildRequires : XStatic-Rickshaw
BuildRequires : XStatic-Spin
BuildRequires : XStatic-bootswatch
BuildRequires : XStatic-jQuery
BuildRequires : XStatic-jquery-ui
BuildRequires : XStatic-mdi
BuildRequires : XStatic-roboto-fontface
BuildRequires : XStatic-smart-table
BuildRequires : XStatic-term.js
BuildRequires : buildreq-distutils3
BuildRequires : django-appconf
BuildRequires : django-babel
BuildRequires : django-nose
BuildRequires : django-pyscss
BuildRequires : django_compressor
BuildRequires : enum34
BuildRequires : eventlet
BuildRequires : httplib2
BuildRequires : iso8601
BuildRequires : kombu
BuildRequires : netaddr
BuildRequires : nose
BuildRequires : oslo.concurrency
BuildRequires : oslo.config
BuildRequires : oslo.i18n
BuildRequires : oslo.policy
BuildRequires : oslo.serialization
BuildRequires : oslo.utils
BuildRequires : pathlib
BuildRequires : pbr
BuildRequires : pip
BuildRequires : prettytable
BuildRequires : pyScss
BuildRequires : python-ceilometerclient
BuildRequires : python-cinderclient
BuildRequires : python-glanceclient
BuildRequires : python-heatclient
BuildRequires : python-keystoneclient
BuildRequires : python-neutronclient
BuildRequires : python-novaclient
BuildRequires : python-saharaclient
BuildRequires : python-swiftclient
BuildRequires : python-troveclient
BuildRequires : python3-dev
BuildRequires : pytz
BuildRequires : rjsmin
BuildRequires : setuptools
BuildRequires : six
BuildRequires : stevedore
Patch1: 0001-enable-dashboard-in-apache.patch
Patch2: 0002-nginx-uwsgi.patch
Patch3: 0001-stateless.patch

%description
Horizon (OpenStack Dashboard)
        =============================
        
        Horizon is a Django-based project aimed at providing a complete OpenStack
        Dashboard along with an extensible framework for building new dashboards
        from reusable components. The ``openstack_dashboard`` module is a reference
        implementation of a Django site that uses the ``horizon`` app to provide
        web-based interactions with the various OpenStack projects.

%package config
Summary: config components for the horizon package.
Group: Default

%description config
config components for the horizon package.


%package license
Summary: license components for the horizon package.
Group: Default

%description license
license components for the horizon package.


%package python
Summary: python components for the horizon package.
Group: Default
Requires: horizon-python3

%description python
python components for the horizon package.


%package python3
Summary: python3 components for the horizon package.
Group: Default
Requires: python3-core

%description python3
python3 components for the horizon package.


%prep
%setup -q -n horizon-13.0.1
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532391562
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
/bin/bash run_tests.sh -N --no-pep8 || :
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/horizon
cp LICENSE %{buildroot}/usr/share/doc/horizon/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/tmpfiles.d/horizon.conf

%files
%defattr(-,root,root,-)

%files config
%defattr(-,root,root,-)
/usr/lib/tmpfiles.d/horizon.conf

%files license
%defattr(-,root,root,-)
/usr/share/doc/horizon/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
